version: '3.7'

services:

  picross-backend:
    container_name: picross-backend-${NODE_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:5555
      - 8000:4000

    volumes:
      - .:/home/node
