version: '2.2'

services:

  picross-backend-api:
    container_name: picross-backend-api-${NODE_ENV}
#    image: aifedespaix/picross-backend
    build:
      context: .
      dockerfile: Dockerfile
#    volumes:
#      - .:/app
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST_API}"
      - "traefik.backend=${TRAEFIK_HOST_API}-back"
      - "traefik.docker.network=web"
      - "traefik.enable=true"

networks:
  web:
    external: true
volumes:
  prod:
